.TH "Builder" 3 "Sat Jan 25 2025" "Sistema de Cadastro de Viagens" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Builder \- Classe responsável por construir e configurar o controlador\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <builder\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBbuild\fP (\fBController\fP *controller)"
.br
.RI "Constrói e configura o controlador\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classe responsável por construir e configurar o controlador\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Builder::build (\fBController\fP * controller)"

.PP
Constrói e configura o controlador\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontroller\fP Ponteiro para o controlador a ser configurado\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Cadastro de Viagens from the source code\&.
