.TH "Controller" 3 "Sat Jan 25 2025" "Sistema de Cadastro de Viagens" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controller \- Classe responsável por gerenciar as views e executar a lógica principal do programa\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <controller\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Controller\fP ()"
.br
.RI "Destrutor da classe \fBController\fP\&. "
.ti -1c
.RI "void \fBsetAuthView\fP (PresentationInterface *authView)"
.br
.RI "Define a view de autenticação\&. "
.ti -1c
.RI "void \fBsetTravelView\fP (PresentationInterface *travelView)"
.br
.RI "Define a view de viagens\&. "
.ti -1c
.RI "void \fBsetDestinationView\fP (PresentationInterface *destinationView)"
.br
.RI "Define a view de destinos\&. "
.ti -1c
.RI "void \fBsetLodgingView\fP (PresentationInterface *lodgingView)"
.br
.RI "Define a view de hospedagem\&. "
.ti -1c
.RI "void \fBsetActivityView\fP (PresentationInterface *activityView)"
.br
.RI "Define a view de atividades\&. "
.ti -1c
.RI "void \fBexecute\fP ()"
.br
.RI "Executa a lógica principal do programa\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Code \fBuserCode\fP = Code('000000')"
.br
.RI "Código do usuário padrão\&. "
.in -1c
.SH "Detailed Description"
.PP 
Classe responsável por gerenciar as views e executar a lógica principal do programa\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Controller::setActivityView (PresentationInterface * activityView)"

.PP
Define a view de atividades\&. 
.PP
\fBParameters\fP
.RS 4
\fIactivityView\fP Ponteiro para a view de atividades\&. 
.RE
.PP

.SS "void Controller::setAuthView (PresentationInterface * authView)"

.PP
Define a view de autenticação\&. 
.PP
\fBParameters\fP
.RS 4
\fIauthView\fP Ponteiro para a view de autenticação\&. 
.RE
.PP

.SS "void Controller::setDestinationView (PresentationInterface * destinationView)"

.PP
Define a view de destinos\&. 
.PP
\fBParameters\fP
.RS 4
\fIdestinationView\fP Ponteiro para a view de destinos\&. 
.RE
.PP

.SS "void Controller::setLodgingView (PresentationInterface * lodgingView)"

.PP
Define a view de hospedagem\&. 
.PP
\fBParameters\fP
.RS 4
\fIlodgingView\fP Ponteiro para a view de hospedagem\&. 
.RE
.PP

.SS "void Controller::setTravelView (PresentationInterface * travelView)"

.PP
Define a view de viagens\&. 
.PP
\fBParameters\fP
.RS 4
\fItravelView\fP Ponteiro para a view de viagens\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Sistema de Cadastro de Viagens from the source code\&.
